language: ruby

cache: bundler

addons:
  postgresql: "9.4"

before_script:
- cp config/tess.example.yml config/tess.yml
- cp config/secrets.travis.yml config/secrets.yml
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:setup
